### ISSUE TITLE
Content provide issue

### ISSUE THREAD

**Issue by ramuind** [Beaconstac/Android-SDK#6]
I have integrated beaconstac in one of my project and it works fine in devices in lollipop and above versions. 

But when I am trying to run it on lower versions , i am getting a issue in MSContentProvider class.

Below is the log.

  java.lang.RuntimeException: Unable to get provider com.sample.mobile.beacon.MyContentProvider: android.content.res.Resources$NotFoundException: String resource ID #0x0
            at android.app.ActivityThread.installProvider(ActivityThread.java:4880)
            at android.app.ActivityThread.installContentProviders(ActivityThread.java:4488)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4428)
            at android.app.ActivityThread.access$1300(ActivityThread.java:145)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5099)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:803)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
            at android.content.res.Resources.getText(Resources.java:236)
            at android.content.res.Resources.getString(Resources.java:320)
            at com.mobstac.beaconstac.provider.MSContentProvider.getAuthority(MSContentProvider.java:37)
            at com.mobstac.beaconstac.provider.MSContentProvider.onCreate(MSContentProvider.java:100)
            at com.sample.mobile.beacon.MyContentProvider.onCreate(MyContentProvider.java:31)
            at android.content.ContentProvider.attachInfo(ContentProvider.java:1058)
            at android.app.ActivityThread.installProvider(ActivityThread.java:4877)
            at android.app.ActivityThread.installContentProviders(ActivityThread.java:4488)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4428)
            at android.app.ActivityThread.access$1300(ActivityThread.java:145)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5099)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:803)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by vibinvarghesemobstac** [comment]
This looks like an issue that arises in the SDK when it tries to get the package name.

Please do try a clean build of your project.

Do let us know if the issue persists.
