### ISSUE TITLE
Getting below exception while accessing the beacon properties of rangedBeacons

### ISSUE THREAD

**Issue by sivaprasadnamburu** [Beaconstac/Android-SDK#8]
11-28 06:05:06.140 17142-17142/com.cyient.imaps E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.cyient.imaps, PID: 17142
                                                                  java.lang.RuntimeException: Error receiving broadcast Intent { act=com.mobstac.beaconstac.intent.action.RANGED_BEACON flg=0x10 (has extras) } in com.cyient.imaps.Indoor2DAnd3DActivity$2@64f53988
                                                                      at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:778)
                                                                      at android.os.Handler.handleCallback(Handler.java:733)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5030)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                   Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@64e6c218: Unmarshalling unknown type code 82 at offset 316
                                                                      at android.os.Parcel.readValue(Parcel.java:2087)
                                                                      at android.os.Parcel.readListInternal(Parcel.java:2362)
                                                                      at android.os.Parcel.readArrayList(Parcel.java:1710)
                                                                      at android.os.Parcel.readValue(Parcel.java:2041)
                                                                      at android.os.Parcel.readArrayMapInternal(Parcel.java:2321)
                                                                      at android.os.Bundle.unparcel(Bundle.java:249)
                                                                      at android.os.Bundle.getParcelableArrayList(Bundle.java:1250)
                                                                      at com.mobstac.beaconstac.core.BeaconstacReceiver.onReceive(BeaconstacReceiver.java:43)
                                                                      at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:768)
                                                                      at android.os.Handler.handleCallback(Handler.java:733) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                      at android.os.Looper.loop(Looper.java:136) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5030) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)

**Comment by kriti-workprofile** [comment]
This error arrises due to incompatibility between the new play services version in the SDK and the older version on your device. The recommended solution is to update to the latest version of Google Play Services. 
You can update it from: http://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-10-0-84-release/
The instructions on how to use the right apk for your device is given on the website.

**Comment by sivaprasadnamburu** [comment]
Hi Kiriti,

I tried the example given in the sdk with my credentials by replacing organisation id, api_key.
Even though I am not getting the beacon id.

Could you check this
